<template>
  <v-content><v-container grid-list-md><v-layout row wrap>
    <v-flex xs6>
      <h2>User: {{staffmember.givenName}} {{staffmember.name}}</h2>
    </v-flex>
    <v-flex xs12>
      <v-expansion-panel expand>
        <v-expansion-panel-content v-for="pg in tasks.projectGroup" :key="pg.key">         
          <div slot="header">
            <div class="caption">Project Group</div>
            <div>{{pg._title}}</div>
          </div>
          <v-expansion-panel expand inset>
            <v-expansion-panel-content v-for="p in pg.project" :key="p.key">
              <div slot="header">
                <v-container fluid><v-layout row wrap>
                  <v-flex>
                    <div class="caption">Project</div>
                    <div>{{p._title}}</div>
                  </v-flex>
                  <v-flex>
                    <div class="text-xs-right">
                      <v-chip v-for="m in p.member" :key="m.staffmemberId">{{m._staffmemberId}}</v-chip>
                    </div>
                  </v-flex>
                </v-layout></v-container>
              </div>
              <v-expansion-panel expand inset>
                <v-expansion-panel-content v-for="tg in p.taskGroup" :key="tg.key">
                  <div slot="header">
                    <div class="caption">Task Group</div>
                    <div>{{tg._title}}</div>
                  </div>
                  <v-expansion-panel-content v-for="t in tg.task" :key="t.key">
                    <div slot="header">
                      <v-container fluid><v-layout row wrap>
                        <v-flex>
                          <div class="caption">Task</div>
                          <div>{{t._title}}</div>
                        </v-flex>
                        <v-flex>
                          <div class="text-xs-right">
                            <v-chip v-for="m in t.member" :key="m.staffmemberId">{{m._staffmemberId}}</v-chip>
                            <v-btn @click.stop="removeTask(tg.task, t)"><v-icon>delete</v-icon></v-btn>
                          </div>
                        </v-flex>
                      </v-layout></v-container>
                    </div>
                  </v-expansion-panel-content>
                  <v-btn @click="addTask(tg)">add task</v-btn>
                  <v-btn @click="removeTaskGroup(p.taskGroup, tg)"><v-icon>delete</v-icon></v-btn>
                </v-expansion-panel-content>
              </v-expansion-panel>
              <v-btn @click="addTaskGroup(p)">add task group</v-btn>
              <v-expansion-panel expand inset>
                <v-expansion-panel-content v-for="t in p.task" :key="t.key">
                  <div slot="header">
                    <v-container fluid><v-layout row wrap>
                      <v-flex>
                        <div class="caption">Task</div>
                        <div>{{t._title}}</div>
                      </v-flex>
                      <v-flex>
                        <div class="text-xs-right">
                          <v-chip v-for="m in t.member" :key="m.staffmemberId">{{m._staffmemberId}}</v-chip>
                          <v-btn @click.stop="removeTask(p.task, t)"><v-icon>delete</v-icon></v-btn>
                        </div>
                      </v-flex>
                    </v-layout></v-container>
                  </div>
                </v-expansion-panel-content>
              </v-expansion-panel>
              <v-btn @click="addTask(p)">add task</v-btn>
              <v-btn @click="removeProject(pg.project, p)"><v-icon>delete</v-icon></v-btn>
            </v-expansion-panel-content>
          </v-expansion-panel>
          <v-btn @click="addProject(pg)">add project</v-btn>
          <v-btn @click="removeProjectGroup(pg)"><v-icon>delete</v-icon></v-btn>
        </v-expansion-panel-content>
      </v-expansion-panel>
      <v-btn @click="addProjectGroup">add project group</v-btn>
    </v-flex>
  </v-layout></v-container></v-content>
</template>

<script>
  import Vue from 'vue'
  import pageMixin from '@/views/PageMixin.js'
  
  // eslint-disable-next-line
  const x2jsTasks = new X2JS({
    arrayAccessFormPaths : [
      /.+.projectGroup/,
      /.+.project/,
      /.+.member/,
      /.+.taskGroup/,
      /.+.task/
    ]
  });
  
  // TODO: keys should be generated by the backend. All items here would probably need an @id, not just tasks. 
  //   Collisions must be avoided
  // page scope unique key generator
  let pskey = 0
  
  export default Vue.component('task-managing-page', {
    mixins: [pageMixin],
    data: function() {
      return {
        tasks: {
        }
      };
    },
    created: function () {
      this.loadData();
    },
    methods: {
      addProjectGroup: function() {
        console.log("addProjectGroup")
        const pg = {
          _customerId: "",
          _title: "new project group",
          key: pskey++
        }
        if (! this.tasks.projectGroup) {
          console.log("creating projectGroup array")
          Vue.set(this.tasks, "projectGroup", [])
        }
        this.tasks.projectGroup.push(pg)
      },
      addProject: function(pg) {
        console.log("addProject")
        const p = {
          _status: "new",
          _priority: "normal",
          _title: "new project",
          key: pskey++
        }
        if (! pg.project) {
          console.log("creating project array")
          Vue.set(pg, "project", [])
        }
        pg.project.push(p)
      },
      addTaskGroup: function(p) {
        console.log("addTaskGroup")
        const tg = {
          _title: "new task group",
          key: pskey++
        }
        if (! p.taskGroup) {
          console.log("creating taskGroup array")
          Vue.set(p, "taskGroup", [])
        }
        p.taskGroup.push(tg)
      },
      addTask: function(p) {
        // note: p may be a project or a task group
        console.log("addTask")
        const t = {
          _id: "",
          _title: "new task",
          _billableDefault: "depends",
          key: pskey++
        }
        if (! p.task) {
          console.log("creating task array")
          Vue.set(p, "task", [])
        }
        p.task.push(t)
      },
      removeProjectGroup: function(pg) {
        console.log("removeProjectGroup")
        this.tasks.projectGroup.splice(this.tasks.projectGroup.indexOf(pg), 1)
      },
      removeProject: function(pArr, p) {
        console.log("removeProject")
        pArr.splice(pArr.indexOf(p), 1)
      },
      removeTaskGroup: function(pArr, tg) {
        console.log("removeTaskGroup")
        pArr.splice(pArr.indexOf(tg), 1)
      },
      removeTask: function(pArr, t) {
        console.log("removeTask")
        pArr.splice(pArr.indexOf(t), 1)
      },
      loadData: function() {
        console.log("loadData")
        const self = this
        self.server.get('../api/tasks/').then(function(taskResponse) {
          console.log("tasks:")
          console.log(taskResponse);
          const t = x2jsTasks.xml_str2json(taskResponse.data).tasks;
          console.log(t)
          self.tasks = t
          self.showMessage('fetched!', 'info')
        }).catch(function (error) {
          if (error.response) {
            // The request was made and the server responded with a status code
            // that falls out of the range of 2xx
            console.log(error.response.data);
            console.log(error.response.status);
            console.log(error.response.headers);
            self.showMessage("ERROR " + error.response.status + ": " + error.response.data, 'error')
          } else if (error.request) {
            // The request was made but no response was received
            // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
            // http.ClientRequest in node.js
            console.log(error.request);
            self.showMessage("ERROR : Failed contacting server", 'error')
          } else {
            // Something happened in setting up the request that triggered an Error
            console.log('Error', error.message);
            self.showMessage("ERROR : Failed setting up server request", 'error')
          }
        });
      }
    }
  })
</script>
